football_dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: /opt/airflow/data/football.db
      schema: main
      schema_directory: /opt/airflow/data
      schemas_and_paths:
        main: /opt/airflow/data/football.db